/**
 * pje-comum
 * Copyright (C) 2009-2013 Conselho Nacional de Justiça
 *
 * A propriedade intelectual deste programa, como código-fonte
 * e como sua derivação compilada, pertence à União Federal,
 * dependendo o uso parcial ou total de autorização expressa do
 * Conselho Nacional de Justiça.
 *
 **/
package br.jus.pje.nucleo.entidades;

// Generated 14/08/2009 11:25:37 by Hibernate Tools 3.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;


/**
 * ProcessoAssunto generated by hiran
 */
@Entity
@Table(name = "tb_agendamento_remessa")
@org.hibernate.annotations.GenericGenerator(name = "gen_agend_remessa", strategy = "br.jus.pje.nucleo.entidades.util.SequencePooledGenerator", parameters = {
		@org.hibernate.annotations.Parameter(name = "sequence", value = "sq_tb_agendamento_remessa"),
		@org.hibernate.annotations.Parameter(name = "allocationSize", value = "-1")})
public class AgendamentoRemessa implements java.io.Serializable, br.jus.pje.nucleo.entidades.IEntidade<AgendamentoRemessa,Integer> {

	private static final long serialVersionUID = 1L;

	private int idAgendamentoRemessa;
	private ProcessoTrf processoTrf;
	private Fluxo fluxo;
	private boolean processado;

	public AgendamentoRemessa() {
	}

	@Id
	@GeneratedValue(generator = "gen_agend_remessa")
	@Column(name = "id_agendamento_remessa", unique = true, nullable = false)
	public int getIdAgendamentoRemessa() {
		return idAgendamentoRemessa;
	}

	public void setIdAgendamentoRemessa(int idAgendamentoRemessa) {
		this.idAgendamentoRemessa = idAgendamentoRemessa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_processo")
	public ProcessoTrf getProcessoTrf() {
		return this.processoTrf;
	}

	public void setProcessoTrf(ProcessoTrf processoTrf) {
		this.processoTrf = processoTrf;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_fluxo")
	public Fluxo getFluxo() {
		return fluxo;
	}

	public void setFluxo(Fluxo fluxo) {
		this.fluxo = fluxo;
	}

	@Column(name = "in_processado", nullable = false)
	@NotNull
	public boolean getProcessado() {
		return processado;
	}

	public void setProcessado(boolean processado) {
		this.processado = processado;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof AgendamentoRemessa)) {
			return false;
		}
		AgendamentoRemessa other = (AgendamentoRemessa) obj;
		if (getIdAgendamentoRemessa() != other.getIdAgendamentoRemessa()) {
			return false;
		}
		return true;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + getIdAgendamentoRemessa();
		return result;
	}

	@Override
	public String toString() {
		if (getIdAgendamentoRemessa() > 0) {
			return getProcessoTrf() + " / " + getFluxo();
		} else {
			return String.valueOf(getIdAgendamentoRemessa());
		}
	}
	
	@Override
	@javax.persistence.Transient
	public Class<? extends AgendamentoRemessa> getEntityClass() {
		return AgendamentoRemessa.class;
	}

	@Override
	@javax.persistence.Transient
	public Integer getEntityIdObject() {
		return Integer.valueOf(getIdAgendamentoRemessa());
	}

	@Override
	@javax.persistence.Transient
	public boolean isLoggable() {
		return true;
	}

}
