//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.27 at 12:29:35 AM BRST 
//

package br.org.oab.www5.cnaws.xmlobj;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}AdvogadoData"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "advogadoData" })
@XmlRootElement(name = "ArrayOfAdvogadoData")
public class ArrayOfAdvogadoData {

	@XmlElement(name = "AdvogadoData", required = true)
	protected List<AdvogadoData> advogadoData;

	/**
	 * Gets the value of the advogadoData property.
	 * 
	 * @return possible object is {@link AdvogadoData }
	 * 
	 */
	public List<AdvogadoData> getAdvogadoData() {
		if (this.advogadoData == null) {
			this.advogadoData = new ArrayList<AdvogadoData>();
		}
		return this.advogadoData;
	}

	/**
	 * Sets the value of the advogadoData property.
	 * 
	 * @param value
	 *            allowed object is {@link AdvogadoData }
	 * 
	 */
	public void setAdvogadoData(List<AdvogadoData> value) {
		this.advogadoData = value;
	}

}
