/**
 * pje-comum
 * Copyright (C) 2009-2013 Conselho Nacional de Justiça
 *
 * A propriedade intelectual deste programa, como código-fonte
 * e como sua derivação compilada, pertence à União Federal,
 * dependendo o uso parcial ou total de autorização expressa do
 * Conselho Nacional de Justiça.
 *
 **/
package br.jus.pje.nucleo.entidades;

import java.util.Calendar;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * BaseCalculoIr generated by Silas
 */
@Entity
@Table(name = BaseCalculoIr.TABLE_NAME)
@org.hibernate.annotations.GenericGenerator(name = "gen_base_calculo_ir", strategy = "br.jus.pje.nucleo.entidades.util.SequencePooledGenerator", parameters = {
		@org.hibernate.annotations.Parameter(name = "sequence", value = "sq_tb_base_calculo_ir"),
		@org.hibernate.annotations.Parameter(name = "allocationSize", value = "-1")})
public class BaseCalculoIr implements java.io.Serializable, br.jus.pje.nucleo.entidades.IEntidade<BaseCalculoIr,Integer> {

	public static final String TABLE_NAME = "tb_base_calculo_ir";
	private static final long serialVersionUID = 1L;

	private int idBaseCalculoIr;
	private Double vlBaseCalculoIrMinimo;
	private Double vlBaseCalculoIrMaximo;
	private Double vlAliquota;
	private Double vlParcelaADeduzir;
	private Date dataInicioVigencia;
	private Date dataFimVigencia;

	@Id
	@GeneratedValue(generator = "gen_base_calculo_ir")
	@Column(name = "id_base_calculo_ir", unique = true, nullable = false)
	public int getIdBaseCalculoIr() {
		return idBaseCalculoIr;
	}

	public void setIdBaseCalculoIr(int idBaseCalculoIr) {
		this.idBaseCalculoIr = idBaseCalculoIr;
	}

	@Column(name = "vl_base_calculo_ir_minimo", nullable = false)
	public Double getVlBaseCalculoIrMinimo() {
		return vlBaseCalculoIrMinimo;
	}

	public void setVlBaseCalculoIrMinimo(Double vlBaseCalculoIrMinimo) {
		this.vlBaseCalculoIrMinimo = vlBaseCalculoIrMinimo;
	}

	@Column(name = "vl_base_calculo_ir_maximo")
	public Double getVlBaseCalculoIrMaximo() {
		return vlBaseCalculoIrMaximo;
	}

	public void setVlBaseCalculoIrMaximo(Double vlBaseCalculoIrMaximo) {
		this.vlBaseCalculoIrMaximo = vlBaseCalculoIrMaximo;
	}

	@Column(name = "vl_aliquota")
	public Double getVlAliquota() {
		return vlAliquota;
	}

	public void setVlAliquota(Double vlAliquota) {
		this.vlAliquota = vlAliquota;
	}

	@Column(name = "vl_parcela_a_deduzir")
	public Double getVlParcelaADeduzir() {
		return vlParcelaADeduzir;
	}

	public void setVlParcelaADeduzir(Double vlParcelaADeduzir) {
		this.vlParcelaADeduzir = vlParcelaADeduzir;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_inicio_vigencia")
	public Date getDataInicioVigencia() {
		return dataInicioVigencia;
	}

	public void setDataInicioVigencia(Date dataInicioVigencia) {
		this.dataInicioVigencia = dataInicioVigencia;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_final_vigencia")
	public Date getDataFimVigencia() {
		return dataFimVigencia;
	}

	public void setDataFimVigencia(Date dataFimVigencia) {
		this.dataFimVigencia = dataFimVigencia;
	}

	@Transient
	public String getConcatDateStr() {
		Calendar dI = Calendar.getInstance();
		dI.setTime(getDataInicioVigencia());
		Calendar dF = Calendar.getInstance();
		dF.setTime(getDataFimVigencia());
		int mesI = dI.get(Calendar.MONTH) + 1;
		int mesF = dF.get(Calendar.MONTH) + 1;
		if (getDataFimVigencia() != null) {
			return ("De: " + dI.get(Calendar.DAY_OF_MONTH) + "/" + mesI + "/" + dI.get(Calendar.YEAR) + " a "
					+ dF.get(Calendar.DAY_OF_MONTH) + "/" + mesF + "/" + dF.get(Calendar.YEAR));
		} else {
			return (dI.get(Calendar.DAY_OF_MONTH) + "/" + dI.get((Calendar.MONTH) + 1) + "/" + dI.get(Calendar.YEAR));
		}
	}
	
	@Override
	@javax.persistence.Transient
	public Class<? extends BaseCalculoIr> getEntityClass() {
		return BaseCalculoIr.class;
	}

	@Override
	@javax.persistence.Transient
	public Integer getEntityIdObject() {
		return Integer.valueOf(getIdBaseCalculoIr());
	}

	@Override
	@javax.persistence.Transient
	public boolean isLoggable() {
		return true;
	}

}
