package br.com.infox.pje.webservices.estatisticaEventoProcessoTrf.client;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3.2-02/08/2010 05:22
 * PM(mockbuild)-SNAPSHOT Generated source version: 2.0
 * 
 */
@WebService(name = "ColetorEventoProcessoVara", targetNamespace = "http://estatisticaEventoProcessoTrf.webservices.pje.infox.com.br/")
public interface ColetorEventoProcessoVara {

	/**
	 * 
	 * @return returns java.util.List<br.com.infox.pje.webservices.estatisticaEventoProcessoTrf.client.EstatisticaEventoProcessoBean>
	 * @throws UnsupportedEncodingException_Exception
	 * @throws NoSuchAlgorithmException_Exception
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "obterEventosProcessos", targetNamespace = "http://estatisticaEventoProcessoTrf.webservices.pje.infox.com.br/", className = "br.com.infox.pje.webservices.estatisticaEventoProcessoTrf.client.ObterEventosProcessos")
	@ResponseWrapper(localName = "obterEventosProcessosResponse", targetNamespace = "http://estatisticaEventoProcessoTrf.webservices.pje.infox.com.br/", className = "br.com.infox.pje.webservices.estatisticaEventoProcessoTrf.client.ObterEventosProcessosResponse")
	public List<EstatisticaEventoProcessoBean> obterEventosProcessos() throws NoSuchAlgorithmException_Exception,
			UnsupportedEncodingException_Exception;

}
