package br.jus.cnj.pje.webservice.client.consultacpf;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2-b05- Generated
 * source version: 2.2
 * 
 */
@WebServiceClient(name = "ConsultarCPF", targetNamespace = "nsProxyRFBCNJ", wsdlLocation = "https://www.cnj.jus.br/testeReceitaFederal/wsdl/proxyReceita.wsdl")
public class ConsultarCPF extends Service {

	private final static URL CONSULTARCPF_WSDL_LOCATION;
	private final static WebServiceException CONSULTARCPF_EXCEPTION;
	private final static QName CONSULTARCPF_QNAME = new QName(
			"nsProxyRFBCNJ", "ConsultarCPF");

	static {
		CONSULTARCPF_WSDL_LOCATION = br.jus.cnj.pje.webservice.client.consultacpf.ConsultarCPF.class
				.getResource("proxyReceita.wsdl");
		WebServiceException e = null;
		if (CONSULTARCPF_WSDL_LOCATION == null) {
			e = new WebServiceException(
					"Cannot find 'https://www.cnj.jus.br/testeReceitaFederal/wsdl/proxyReceita.wsdl' wsdl. Place the resource correctly in the classpath.");
		}
		CONSULTARCPF_EXCEPTION = e;
	}

	public ConsultarCPF() {
		super(__getWsdlLocation(), CONSULTARCPF_QNAME);
	}

	/*
	 * public ConsultarCPF(WebServiceFeature... features) {
	 * super(__getWsdlLocation(), CONSULTARCPF_QNAME, features); }
	 */

	public ConsultarCPF(URL wsdlLocation) {
		super(wsdlLocation, CONSULTARCPF_QNAME);
	}

	/*
	 * public ConsultarCPF(URL wsdlLocation, WebServiceFeature... features) {
	 * super(wsdlLocation, CONSULTARCPF_QNAME, features); }
	 */
	public ConsultarCPF(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	/*
	 * public ConsultarCPF(URL wsdlLocation, QName serviceName,
	 * WebServiceFeature... features) { super(wsdlLocation, serviceName,
	 * features); }
	 */
	/**
	 * 
	 * @return returns ConsultarCPFSoap
	 */
	@WebEndpoint(name = "ConsultarCPFSoap")
	public ConsultarCPFSoap getConsultarCPFSoap() {
		return super.getPort(new QName("nsProxyRFBCNJ",
				"ConsultarCPFSoap"), ConsultarCPFSoap.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *            on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default
	 *            values.
	 * @return returns ConsultarCPFSoap
	 */
	@WebEndpoint(name = "ConsultarCPFSoap")
	public ConsultarCPFSoap getConsultarCPFSoap(WebServiceFeature... features) {
		return super.getPort(new QName("nsProxyRFBCNJ",
				"ConsultarCPFSoap"), ConsultarCPFSoap.class, features);
	}

	private static URL __getWsdlLocation() {
		if (CONSULTARCPF_EXCEPTION != null) {
			throw CONSULTARCPF_EXCEPTION;
		}
		return CONSULTARCPF_WSDL_LOCATION;
	}

}
