package br.jus.cnj.pje.webservice.client.consultacnpj;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2-b05- Generated
 * source version: 2.2
 * 
 */
@WebService(name = "ConsultarCNPJSoap", targetNamespace = "nsProxyRFBCNJ")
@XmlSeeAlso({ ObjectFactory.class })
public interface ConsultarCNPJSoap {

	/**
	 * Consultar CNPJ - Perfil 1
	 * 
	 * @param cpfUsuario
	 * @param cnpj
	 * @return returns
	 *         br.jus.pje.ws.externo.srfb.util.consultacnpj.ArrayOfCNPJPerfil1
	 */
	@WebMethod(operationName = "ConsultarCNPJP1", action = "nsProxyRFBCNJ#ConsultarCNPJP1")
	@WebResult(name = "ConsultarCNPJP1Result", targetNamespace = "nsProxyRFBCNJ")
	@RequestWrapper(localName = "ConsultarCNPJP1", targetNamespace = "nsProxyRFBCNJ", className = "br.jus.pje.ws.externo.srfb.util.consultacnpj.ConsultarCNPJP1")
	@ResponseWrapper(localName = "ConsultarCNPJP1Response", targetNamespace = "nsProxyRFBCNJ", className = "br.jus.pje.ws.externo.srfb.util.consultacnpj.ConsultarCNPJP1Response")
	public ArrayOfCNPJPerfil1 consultarCNPJP1(
			@WebParam(name = "CNPJ", targetNamespace = "nsProxyRFBCNJ") String cnpj,
			@WebParam(name = "CPFUsuario", targetNamespace = "nsProxyRFBCNJ") String cpfUsuario);

	/**
	 * Consultar Teste CNPJ - Perfil 1
	 * 
	 * @param cpfUsuario
	 * @param cnpj
	 * @return returns
	 *         br.jus.pje.ws.externo.srfb.util.consultacnpj.ArrayOfCNPJPerfil1
	 */
	@WebMethod(operationName = "ConsultarCNPJP1T", action = "nsProxyRFBCNJ#ConsultarCNPJP1T")
	@WebResult(name = "ConsultarCNPJP1TResult", targetNamespace = "nsProxyRFBCNJ")
	@RequestWrapper(localName = "ConsultarCNPJP1T", targetNamespace = "nsProxyRFBCNJ", className = "br.jus.pje.ws.externo.srfb.util.consultacnpj.ConsultarCNPJP1T")
	@ResponseWrapper(localName = "ConsultarCNPJP1TResponse", targetNamespace = "nsProxyRFBCNJ", className = "br.jus.pje.ws.externo.srfb.util.consultacnpj.ConsultarCNPJP1TResponse")
	public ArrayOfCNPJPerfil1 consultarCNPJP1T(
			@WebParam(name = "CNPJ", targetNamespace = "nsProxyRFBCNJ") String cnpj,
			@WebParam(name = "CPFUsuario", targetNamespace = "nsProxyRFBCNJ") String cpfUsuario);

	/**
	 * Consultar CNPJ - Perfil 2
	 * 
	 * @param cpfUsuario
	 * @param cnpj
	 * @return returns
	 *         br.jus.pje.ws.externo.srfb.util.consultacnpj.ArrayOfCNPJPerfil2
	 */
	@WebMethod(operationName = "ConsultarCNPJP2", action = "nsProxyRFBCNJ#ConsultarCNPJP2")
	@WebResult(name = "ConsultarCNPJP2Result", targetNamespace = "nsProxyRFBCNJ")
	@RequestWrapper(localName = "ConsultarCNPJP2", targetNamespace = "nsProxyRFBCNJ", className = "br.jus.pje.ws.externo.srfb.util.consultacnpj.ConsultarCNPJP2")
	@ResponseWrapper(localName = "ConsultarCNPJP2Response", targetNamespace = "nsProxyRFBCNJ", className = "br.jus.pje.ws.externo.srfb.util.consultacnpj.ConsultarCNPJP2Response")
	public ArrayOfCNPJPerfil2 consultarCNPJP2(
			@WebParam(name = "CNPJ", targetNamespace = "nsProxyRFBCNJ") String cnpj,
			@WebParam(name = "CPFUsuario", targetNamespace = "nsProxyRFBCNJ") String cpfUsuario);

	/**
	 * Consultar Teste CNPJ - Perfil 2
	 * 
	 * @param cpfUsuario
	 * @param cnpj
	 * @return returns
	 *         br.jus.pje.ws.externo.srfb.util.consultacnpj.ArrayOfCNPJPerfil2
	 */
	@WebMethod(operationName = "ConsultarCNPJP2T", action = "nsProxyRFBCNJ#ConsultarCNPJP2T")
	@WebResult(name = "ConsultarCNPJP2TResult", targetNamespace = "nsProxyRFBCNJ")
	@RequestWrapper(localName = "ConsultarCNPJP2T", targetNamespace = "nsProxyRFBCNJ", className = "br.jus.pje.ws.externo.srfb.util.consultacnpj.ConsultarCNPJP2T")
	@ResponseWrapper(localName = "ConsultarCNPJP2TResponse", targetNamespace = "nsProxyRFBCNJ", className = "br.jus.pje.ws.externo.srfb.util.consultacnpj.ConsultarCNPJP2TResponse")
	public ArrayOfCNPJPerfil2 consultarCNPJP2T(
			@WebParam(name = "CNPJ", targetNamespace = "nsProxyRFBCNJ") String cnpj,
			@WebParam(name = "CPFUsuario", targetNamespace = "nsProxyRFBCNJ") String cpfUsuario);

	/**
	 * Consultar CNPJ - Perfil 3
	 * 
	 * @param cpfUsuario
	 * @param cnpj
	 * @return returns
	 *         br.jus.pje.ws.externo.srfb.util.consultacnpj.ArrayOfCNPJPerfil3
	 */
	@WebMethod(operationName = "ConsultarCNPJP3", action = "nsProxyRFBCNJ#ConsultarCNPJP3")
	@WebResult(name = "ConsultarCNPJP3Result", targetNamespace = "nsProxyRFBCNJ")
	@RequestWrapper(localName = "ConsultarCNPJP3", targetNamespace = "nsProxyRFBCNJ", className = "br.jus.pje.ws.externo.srfb.util.consultacnpj.ConsultarCNPJP3")
	@ResponseWrapper(localName = "ConsultarCNPJP3Response", targetNamespace = "nsProxyRFBCNJ", className = "br.jus.pje.ws.externo.srfb.util.consultacnpj.ConsultarCNPJP3Response")
	public ArrayOfCNPJPerfil3 consultarCNPJP3(
			@WebParam(name = "CNPJ", targetNamespace = "nsProxyRFBCNJ") String cnpj,
			@WebParam(name = "CPFUsuario", targetNamespace = "nsProxyRFBCNJ") String cpfUsuario);

	/**
	 * Consultar Teste CNPJ - Perfil 3
	 * 
	 * @param cpfUsuario
	 * @param cnpj
	 * @return returns
	 *         br.jus.pje.ws.externo.srfb.util.consultacnpj.ArrayOfCNPJPerfil3
	 */
	@WebMethod(operationName = "ConsultarCNPJP3T", action = "nsProxyRFBCNJ#ConsultarCNPJP3T")
	@WebResult(name = "ConsultarCNPJP3TResult", targetNamespace = "nsProxyRFBCNJ")
	@RequestWrapper(localName = "ConsultarCNPJP3T", targetNamespace = "nsProxyRFBCNJ", className = "br.jus.pje.ws.externo.srfb.util.consultacnpj.ConsultarCNPJP3T")
	@ResponseWrapper(localName = "ConsultarCNPJP3TResponse", targetNamespace = "nsProxyRFBCNJ", className = "br.jus.pje.ws.externo.srfb.util.consultacnpj.ConsultarCNPJP3TResponse")
	public ArrayOfCNPJPerfil3 consultarCNPJP3T(
			@WebParam(name = "CNPJ", targetNamespace = "nsProxyRFBCNJ") String cnpj,
			@WebParam(name = "CPFUsuario", targetNamespace = "nsProxyRFBCNJ") String cpfUsuario);

}
