package br.jus.cnj.pje.webservice.client.consultacnpj;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2-b05- Generated
 * source version: 2.2
 * 
 */
@WebServiceClient(name = "ConsultarCNPJ", targetNamespace = "nsProxyRFBCNJ", wsdlLocation = "https://www.cnj.jus.br/testeReceitaFederal/wsdl/proxyReceitaCNPJ.wsdl")
public class ConsultarCNPJ extends Service {

	private final static URL CONSULTARCNPJ_WSDL_LOCATION;
	private final static WebServiceException CONSULTARCNPJ_EXCEPTION;
	private final static QName CONSULTARCNPJ_QNAME = new QName(
			"nsProxyRFBCNJ", "ConsultarCNPJ");

	static {
		CONSULTARCNPJ_WSDL_LOCATION = br.jus.cnj.pje.webservice.client.consultacnpj.ConsultarCNPJ.class
				.getResource("https://www.cnj.jus.br/testeReceitaFederal/wsdl/proxyReceitaCNPJ.wsdl");
		WebServiceException e = null;
		if (CONSULTARCNPJ_WSDL_LOCATION == null) {
			e = new WebServiceException(
					"Cannot find 'https://www.cnj.jus.br/testeReceitaFederal/wsdl/proxyReceitaCNPJ.wsdl' wsdl. Place the resource correctly in the classpath.");
		}
		CONSULTARCNPJ_EXCEPTION = e;
	}

	public ConsultarCNPJ() {
		super(__getWsdlLocation(), CONSULTARCNPJ_QNAME);
	}

	/*
	 * public ConsultarCNPJ(WebServiceFeature... features) {
	 * super(__getWsdlLocation(), CONSULTARCNPJ_QNAME, features); }
	 */
	public ConsultarCNPJ(URL wsdlLocation) {
		super(wsdlLocation, CONSULTARCNPJ_QNAME);
	}

	/*
	 * public ConsultarCNPJ(URL wsdlLocation, WebServiceFeature... features) {
	 * super(wsdlLocation, CONSULTARCNPJ_QNAME, features); }
	 */
	public ConsultarCNPJ(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	/*
	 * public ConsultarCNPJ(URL wsdlLocation, QName serviceName,
	 * WebServiceFeature... features) { super(wsdlLocation, serviceName,
	 * features); }
	 */
	/**
	 * 
	 * @return returns ConsultarCNPJSoap
	 */
	@WebEndpoint(name = "ConsultarCNPJSoap")
	public ConsultarCNPJSoap getConsultarCNPJSoap() {
		return super.getPort(new QName("nsProxyRFBCNJ",
				"ConsultarCNPJSoap"), ConsultarCNPJSoap.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *            on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default
	 *            values.
	 * @return returns ConsultarCNPJSoap
	 */
	@WebEndpoint(name = "ConsultarCNPJSoap")
	public ConsultarCNPJSoap getConsultarCNPJSoap(WebServiceFeature... features) {
		return super.getPort(new QName("nsProxyRFBCNJ",
				"ConsultarCNPJSoap"), ConsultarCNPJSoap.class, features);
	}

	private static URL __getWsdlLocation() {
		if (CONSULTARCNPJ_EXCEPTION != null) {
			throw CONSULTARCNPJ_EXCEPTION;
		}
		return CONSULTARCNPJ_WSDL_LOCATION;
	}

}
