package br.jus.cnj.pje.webservice.client.consultacpf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2-b05- Generated
 * source version: 2.2
 * 
 */
@WebService(name = "ConsultarCPFSoap", targetNamespace = "nsProxyRFBCNJ")
@XmlSeeAlso({ ObjectFactory.class })
public interface ConsultarCPFSoap {

	/**
	 * Consultar CPF - Perfil 1
	 * 
	 * @param listaDeCPF
	 * @param cpfUsuario
	 * @return returns
	 *         br.jus.pje.ws.externo.srfb.util.consultacpf.ArrayOfPessoaPerfil1
	 */
	@WebMethod(operationName = "ConsultarCPFP1", action = "nsProxyRFBCNJ#ConsultarCPFP1")
	@WebResult(name = "ConsultarCPFP1Result", targetNamespace = "nsProxyRFBCNJ")
	@RequestWrapper(localName = "ConsultarCPFP1", targetNamespace = "nsProxyRFBCNJ", className = "br.jus.pje.ws.externo.srfb.util.consultacpf.ConsultarCPFP1")
	@ResponseWrapper(localName = "ConsultarCPFP1Response", targetNamespace = "nsProxyRFBCNJ", className = "br.jus.pje.ws.externo.srfb.util.consultacpf.ConsultarCPFP1Response")
	public ArrayOfPessoaPerfil1 consultarCPFP1(
			@WebParam(name = "ListaDeCPF", targetNamespace = "nsProxyRFBCNJ") String listaDeCPF,
			@WebParam(name = "CPFUsuario", targetNamespace = "nsProxyRFBCNJ") String cpfUsuario);

	/**
	 * Consultar Teste CPF - Perfil 1
	 * 
	 * @param listaDeCPF
	 * @param cpfUsuario
	 * @return returns
	 *         br.jus.pje.ws.externo.srfb.util.consultacpf.ArrayOfPessoaPerfil1
	 */
	@WebMethod(operationName = "ConsultarCPFP1T", action = "nsProxyRFBCNJ#ConsultarCPFP1T")
	@WebResult(name = "ConsultarCPFP1TResult", targetNamespace = "nsProxyRFBCNJ")
	@RequestWrapper(localName = "ConsultarCPFP1T", targetNamespace = "nsProxyRFBCNJ", className = "br.jus.pje.ws.externo.srfb.util.consultacpf.ConsultarCPFP1T")
	@ResponseWrapper(localName = "ConsultarCPFP1TResponse", targetNamespace = "nsProxyRFBCNJ", className = "br.jus.pje.ws.externo.srfb.util.consultacpf.ConsultarCPFP1TResponse")
	public ArrayOfPessoaPerfil1 consultarCPFP1T(
			@WebParam(name = "ListaDeCPF", targetNamespace = "nsProxyRFBCNJ") String listaDeCPF,
			@WebParam(name = "CPFUsuario", targetNamespace = "nsProxyRFBCNJ") String cpfUsuario);

	/**
	 * Consultar CPF - Perfil 2
	 * 
	 * @param listaDeCPF
	 * @param cpfUsuario
	 * @return returns
	 *         br.jus.pje.ws.externo.srfb.util.consultacpf.ArrayOfPessoaPerfil2
	 */
	@WebMethod(operationName = "ConsultarCPFP2", action = "nsProxyRFBCNJ#ConsultarCPFP2")
	@WebResult(name = "ConsultarCPFP2Result", targetNamespace = "nsProxyRFBCNJ")
	@RequestWrapper(localName = "ConsultarCPFP2", targetNamespace = "nsProxyRFBCNJ", className = "br.jus.pje.ws.externo.srfb.util.consultacpf.ConsultarCPFP2")
	@ResponseWrapper(localName = "ConsultarCPFP2Response", targetNamespace = "nsProxyRFBCNJ", className = "br.jus.pje.ws.externo.srfb.util.consultacpf.ConsultarCPFP2Response")
	public ArrayOfPessoaPerfil2 consultarCPFP2(
			@WebParam(name = "ListaDeCPF", targetNamespace = "nsProxyRFBCNJ") String listaDeCPF,
			@WebParam(name = "CPFUsuario", targetNamespace = "nsProxyRFBCNJ") String cpfUsuario);

	/**
	 * Consultar Teste CPF - Perfil 2
	 * 
	 * @param listaDeCPF
	 * @param cpfUsuario
	 * @return returns
	 *         br.jus.pje.ws.externo.srfb.util.consultacpf.ArrayOfPessoaPerfil2
	 */
	@WebMethod(operationName = "ConsultarCPFP2T", action = "nsProxyRFBCNJ#ConsultarCPFP2T")
	@WebResult(name = "ConsultarCPFP2TResult", targetNamespace = "nsProxyRFBCNJ")
	@RequestWrapper(localName = "ConsultarCPFP2T", targetNamespace = "nsProxyRFBCNJ", className = "br.jus.pje.ws.externo.srfb.util.consultacpf.ConsultarCPFP2T")
	@ResponseWrapper(localName = "ConsultarCPFP2TResponse", targetNamespace = "nsProxyRFBCNJ", className = "br.jus.pje.ws.externo.srfb.util.consultacpf.ConsultarCPFP2TResponse")
	public ArrayOfPessoaPerfil2 consultarCPFP2T(
			@WebParam(name = "ListaDeCPF", targetNamespace = "nsProxyRFBCNJ") String listaDeCPF,
			@WebParam(name = "CPFUsuario", targetNamespace = "nsProxyRFBCNJ") String cpfUsuario);

	/**
	 * Consultar CPF - Perfil 3
	 * 
	 * @param listaDeCPF
	 * @param cpfUsuario
	 * @return returns
	 *         br.jus.pje.ws.externo.srfb.util.consultacpf.ArrayOfPessoaPerfil3
	 */
	@WebMethod(operationName = "ConsultarCPFP3", action = "nsProxyRFBCNJ#ConsultarCPFP3")
	@WebResult(name = "ConsultarCPFP3Result", targetNamespace = "nsProxyRFBCNJ")
	@RequestWrapper(localName = "ConsultarCPFP3", targetNamespace = "nsProxyRFBCNJ", className = "br.jus.pje.ws.externo.srfb.util.consultacpf.ConsultarCPFP3")
	@ResponseWrapper(localName = "ConsultarCPFP3Response", targetNamespace = "nsProxyRFBCNJ", className = "br.jus.pje.ws.externo.srfb.util.consultacpf.ConsultarCPFP3Response")
	public ArrayOfPessoaPerfil3 consultarCPFP3(
			@WebParam(name = "ListaDeCPF", targetNamespace = "nsProxyRFBCNJ") String listaDeCPF,
			@WebParam(name = "CPFUsuario", targetNamespace = "nsProxyRFBCNJ") String cpfUsuario);

	/**
	 * Consultar Teste CPF - Perfil 3
	 * 
	 * @param listaDeCPF
	 * @param cpfUsuario
	 * @return returns
	 *         br.jus.pje.ws.externo.srfb.util.consultacpf.ArrayOfPessoaPerfil3
	 */
	@WebMethod(operationName = "ConsultarCPFP3T", action = "nsProxyRFBCNJ#ConsultarCPFP3T")
	@WebResult(name = "ConsultarCPFP3TResult", targetNamespace = "nsProxyRFBCNJ")
	@RequestWrapper(localName = "ConsultarCPFP3T", targetNamespace = "nsProxyRFBCNJ", className = "br.jus.pje.ws.externo.srfb.util.consultacpf.ConsultarCPFP3T")
	@ResponseWrapper(localName = "ConsultarCPFP3TResponse", targetNamespace = "nsProxyRFBCNJ", className = "br.jus.pje.ws.externo.srfb.util.consultacpf.ConsultarCPFP3TResponse")
	public ArrayOfPessoaPerfil3 consultarCPFP3T(
			@WebParam(name = "ListaDeCPF", targetNamespace = "nsProxyRFBCNJ") String listaDeCPF,
			@WebParam(name = "CPFUsuario", targetNamespace = "nsProxyRFBCNJ") String cpfUsuario);

}
