package br.jus.cnj.mandadoprisao.webservices;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "MandadoPrisaoService", targetNamespace = "http://www.cnj.jus.br/mpws")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MandadoPrisaoService {


    /**
     * 
     * @param chaveAcesso
     * @param mandados
     * @return
     *     returns br.jus.cnj.mpws.Comprovante
     * @throws MandadoPrisaoException_Exception
     */
    @WebMethod(action = "urn:EnviarMandado")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "enviarMandado", targetNamespace = "http://www.cnj.jus.br/mpws", className = "br.jus.cnj.mandadoprisao.webservices.EnviarMandado")
    @ResponseWrapper(localName = "enviarMandadoResponse", targetNamespace = "http://www.cnj.jus.br/mpws", className = "br.jus.cnj.mandadoprisao.webservices.EnviarMandadoResponse")
    public MPWSComprovante enviarMandado(
        @WebParam(name = "mandados", targetNamespace = "")
        List<MPWSMandadoPrisao> mandados,
        @WebParam(name = "chaveAcesso", targetNamespace = "")
        String chaveAcesso)
        throws MandadoPrisaoException_Exception
    ;

    /**
     * 
     * @param situacoes
     * @param chaveAcesso
     * @return
     *     returns br.jus.cnj.mpws.Comprovante
     * @throws MandadoPrisaoException_Exception
     */
    @WebMethod(action = "urn:EnviarSituacaoMandado")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "enviarSituacaoMandado", targetNamespace = "http://www.cnj.jus.br/mpws", className = "br.jus.cnj.mandadoprisao.webservices.EnviarSituacaoMandado")
    @ResponseWrapper(localName = "enviarSituacaoMandadoResponse", targetNamespace = "http://www.cnj.jus.br/mpws", className = "br.jus.cnj.mandadoprisao.webservices.EnviarSituacaoMandadoResponse")
    public MPWSComprovante enviarSituacaoMandado(
        @WebParam(name = "situacoes", targetNamespace = "")
        List<MPWSSituacaoMandado> situacoes,
        @WebParam(name = "chaveAcesso", targetNamespace = "")
        String chaveAcesso)
        throws MandadoPrisaoException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ping", targetNamespace = "http://www.cnj.jus.br/mpws", className = "br.jus.cnj.mandadoprisao.webservices.Ping")
    @ResponseWrapper(localName = "pingResponse", targetNamespace = "http://www.cnj.jus.br/mpws", className = "br.jus.cnj.mandadoprisao.webservices.PingResponse")
    public String ping(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
