package br.jus.cnj.mandadoprisao.webservices;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.6 in JDK 6 Generated
 * source version: 2.1
 * 
 */
@WebServiceClient(name = "MandadoPrisaoServiceWS", targetNamespace = "http://www.cnj.jus.br/mpws", wsdlLocation = "http://localhost:8080/MPWS/mandadoPrisaoService?wsdl")
public class MandadoPrisaoServiceWS extends Service {

	private final static URL MANDADOPRISAOSERVICEWS_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(MandadoPrisaoServiceWS.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = MandadoPrisaoServiceWS.class.getResource(".");
			url = new URL(baseUrl, "http://localhost:8080/MPWS/mandadoPrisaoService?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/MPWS/mandadoPrisaoService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		MANDADOPRISAOSERVICEWS_WSDL_LOCATION = url;
	}

	public MandadoPrisaoServiceWS(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public MandadoPrisaoServiceWS() {
		super(MANDADOPRISAOSERVICEWS_WSDL_LOCATION, new QName("http://www.cnj.jus.br/mpws", "MandadoPrisaoServiceWS"));
	}

	/**
	 * 
	 * @return returns MandadoPrisaoService
	 */
	@WebEndpoint(name = "MandadoPrisaoPortWS")
	public MandadoPrisaoService getMandadoPrisaoPortWS() {
		return super
				.getPort(new QName("http://www.cnj.jus.br/mpws", "MandadoPrisaoPortWS"), MandadoPrisaoService.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *            on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default
	 *            values.
	 * @return returns MandadoPrisaoService
	 */
	@WebEndpoint(name = "MandadoPrisaoPortWS")
	public MandadoPrisaoService getMandadoPrisaoPortWS(WebServiceFeature... features) {
		return super.getPort(new QName("http://www.cnj.jus.br/mpws", "MandadoPrisaoPortWS"),
				MandadoPrisaoService.class, features);
	}

}
