package br.com.infox.pje.webservices.processoprevento;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3.2-06/22/2009 08:27
 * PM(mockbuild)-SNAPSHOT Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "ProcessoPreventoService", targetNamespace = "http://webservices.pje.infox.com.br/", wsdlLocation = "http://172.20.2.79:8080/pje2_dev/ProcessoPrevento?wsdl")
public class ProcessoPreventoService extends Service {

	private final static URL PROCESSOPREVENTOSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(br.com.infox.pje.webservices.processoprevento.ProcessoPreventoService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = br.com.infox.pje.webservices.processoprevento.ProcessoPreventoService.class.getResource(".");
			url = new URL(baseUrl, "http://172.20.2.79:8080/pje2_dev/ProcessoPrevento?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://172.20.2.79:8080/pje2_dev/ProcessoPrevento?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		PROCESSOPREVENTOSERVICE_WSDL_LOCATION = url;
	}

	public ProcessoPreventoService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public ProcessoPreventoService() {
		super(PROCESSOPREVENTOSERVICE_WSDL_LOCATION, new QName("http://webservices.pje.infox.com.br/",
				"ProcessoPreventoService"));
	}

	/**
	 * 
	 * @return returns ProcessoPrevento
	 */
	@WebEndpoint(name = "ProcessoPreventoPort")
	public ProcessoPrevento getProcessoPreventoPort() {
		return super.getPort(new QName("http://webservices.pje.infox.com.br/", "ProcessoPreventoPort"),
				ProcessoPrevento.class);
	}

}
