//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.27 at 09:47:23 PM BRT 
//

package br.jus.csjt.pje.commons.util.dejt;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 * 
 * Processo de uma matéria. Os atributos classe, num, ano,vara,
 * tribunal,sequencial,digito formam o número do processo, como no exemplo
 * abaixo. Exemplo: AIRR - 37/2006-013-08-40.9 <processo classe="AIRR" num="37"
 * ano="2006" vara="013" tribunal="08" sequencial="40" digito="9">
 * 
 * Se o número for do formato anterior apenas com número e ano, os outros campo
 * não devem ser envidos, conforme o exemplo abaixo: Exemplo: <processo
 * classe="AIRR" num="6" ano="1999" digito="4">
 * 
 * O atributo complemento é para ser usado como uma informação complementar do
 * processo, como no exemplo abaixo. Exemplo: <processo classe = "RT" num="106"
 * ano="2007" vara="2" tribunal="20" sequencial="0" digito="1"
 * complemento="CorreJunto AIRR 26/2005-002-20-00-3">
 * 
 * Caso o processo utilize a numeração única é necessário informar outros
 * campos, como no exemplo abaixo. É possível enviar as duas numerações para o
 * mesmo processo. Exemplos: <processo classe="ET" num="4" ano="2002" vara="900"
 * tribunal="02" sequencial="00" digito="0" numUnico="400" digitoUnico="89"
 * anoUnico="2002" tribunalUnico="02" origemUnico="900">
 * 
 * <processo classe="ET" num="107" ano="2001" vara="371" tribunal="05"
 * sequencial="00" digito="1" numUnico="10700" digitoUnico="06" anoUnico="2001"
 * tribunalUnico="05" origemUnico="371">
 * 
 * 
 * 
 * <p>
 * Java class for processoType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="processoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="parte" type="{}parteType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ano">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *             &lt;totalDigits value="4"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="anoUnico">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *             &lt;totalDigits value="4"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="classe">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;whiteSpace value="collapse"/>
 *             &lt;maxLength value="100"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="complemento" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="digito">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;whiteSpace value="collapse"/>
 *             &lt;minLength value="1"/>
 *             &lt;maxLength value="1"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="digitoUnico">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *             &lt;totalDigits value="2"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="link" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="num">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *             &lt;totalDigits value="8"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="numUnico">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *             &lt;totalDigits value="7"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="origemUnico">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *             &lt;totalDigits value="4"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="redator">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;whiteSpace value="collapse"/>
 *             &lt;minLength value="1"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="relator">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;whiteSpace value="collapse"/>
 *             &lt;minLength value="1"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="revisor">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;whiteSpace value="collapse"/>
 *             &lt;minLength value="1"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="sequencial">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *             &lt;totalDigits value="2"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="tribunal">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *             &lt;totalDigits value="2"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="tribunalUnico">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *             &lt;totalDigits value="2"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="vara">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *             &lt;totalDigits value="3"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "processoType", propOrder = { "parte" })
public class ProcessoType {

	@XmlElement(required = true)
	protected List<ParteType> parte;
	@XmlAttribute
	protected BigInteger ano;
	@XmlAttribute
	protected BigInteger anoUnico;
	@XmlAttribute
	protected String classe;
	@XmlAttribute
	protected String complemento;
	@XmlAttribute
	protected String digito;
	@XmlAttribute
	protected BigInteger digitoUnico;
	@XmlAttribute
	protected String link;
	@XmlAttribute
	protected BigInteger num;
	@XmlAttribute
	protected BigInteger numUnico;
	@XmlAttribute
	protected BigInteger origemUnico;
	@XmlAttribute
	protected String redator;
	@XmlAttribute
	protected String relator;
	@XmlAttribute
	protected String revisor;
	@XmlAttribute
	protected BigInteger sequencial;
	@XmlAttribute
	protected BigInteger tribunal;
	@XmlAttribute
	protected BigInteger tribunalUnico;
	@XmlAttribute
	protected BigInteger vara;

	/**
	 * Gets the value of the parte property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the parte property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getParte().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link ParteType }
	 * 
	 * 
	 */
	public List<ParteType> getParte() {
		if (parte == null) {
			parte = new ArrayList<ParteType>();
		}
		return this.parte;
	}

	/**
	 * Gets the value of the ano property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getAno() {
		return ano;
	}

	/**
	 * Sets the value of the ano property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setAno(BigInteger value) {
		this.ano = value;
	}

	/**
	 * Gets the value of the anoUnico property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getAnoUnico() {
		return anoUnico;
	}

	/**
	 * Sets the value of the anoUnico property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setAnoUnico(BigInteger value) {
		this.anoUnico = value;
	}

	/**
	 * Gets the value of the classe property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getClasse() {
		return classe;
	}

	/**
	 * Sets the value of the classe property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setClasse(String value) {
		this.classe = value;
	}

	/**
	 * Gets the value of the complemento property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getComplemento() {
		return complemento;
	}

	/**
	 * Sets the value of the complemento property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setComplemento(String value) {
		this.complemento = value;
	}

	/**
	 * Gets the value of the digito property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDigito() {
		return digito;
	}

	/**
	 * Sets the value of the digito property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDigito(String value) {
		this.digito = value;
	}

	/**
	 * Gets the value of the digitoUnico property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getDigitoUnico() {
		return digitoUnico;
	}

	/**
	 * Sets the value of the digitoUnico property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setDigitoUnico(BigInteger value) {
		this.digitoUnico = value;
	}

	/**
	 * Gets the value of the link property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLink() {
		return link;
	}

	/**
	 * Sets the value of the link property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLink(String value) {
		this.link = value;
	}

	/**
	 * Gets the value of the num property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getNum() {
		return num;
	}

	/**
	 * Sets the value of the num property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setNum(BigInteger value) {
		this.num = value;
	}

	/**
	 * Gets the value of the numUnico property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getNumUnico() {
		return numUnico;
	}

	/**
	 * Sets the value of the numUnico property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setNumUnico(BigInteger value) {
		this.numUnico = value;
	}

	/**
	 * Gets the value of the origemUnico property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getOrigemUnico() {
		return origemUnico;
	}

	/**
	 * Sets the value of the origemUnico property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setOrigemUnico(BigInteger value) {
		this.origemUnico = value;
	}

	/**
	 * Gets the value of the redator property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRedator() {
		return redator;
	}

	/**
	 * Sets the value of the redator property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRedator(String value) {
		this.redator = value;
	}

	/**
	 * Gets the value of the relator property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRelator() {
		return relator;
	}

	/**
	 * Sets the value of the relator property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRelator(String value) {
		this.relator = value;
	}

	/**
	 * Gets the value of the revisor property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRevisor() {
		return revisor;
	}

	/**
	 * Sets the value of the revisor property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRevisor(String value) {
		this.revisor = value;
	}

	/**
	 * Gets the value of the sequencial property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getSequencial() {
		return sequencial;
	}

	/**
	 * Sets the value of the sequencial property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setSequencial(BigInteger value) {
		this.sequencial = value;
	}

	/**
	 * Gets the value of the tribunal property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getTribunal() {
		return tribunal;
	}

	/**
	 * Sets the value of the tribunal property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setTribunal(BigInteger value) {
		this.tribunal = value;
	}

	/**
	 * Gets the value of the tribunalUnico property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getTribunalUnico() {
		return tribunalUnico;
	}

	/**
	 * Sets the value of the tribunalUnico property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setTribunalUnico(BigInteger value) {
		this.tribunalUnico = value;
	}

	/**
	 * Gets the value of the vara property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getVara() {
		return vara;
	}

	/**
	 * Sets the value of the vara property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setVara(BigInteger value) {
		this.vara = value;
	}

}
