/**
 * pje-comum
 * Copyright (C) 2009-2013 Conselho Nacional de Justiça
 *
 * A propriedade intelectual deste programa, como código-fonte
 * e como sua derivação compilada, pertence à União Federal,
 * dependendo o uso parcial ou total de autorização expressa do
 * Conselho Nacional de Justiça.
 *
 **/
package br.jus.pje.nucleo.entidades;

// Generated 30/10/2008 07:40:27 by Hibernate Tools 3.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Transient;


/**
 * TipoProcessoDocumentoTrf generated by hbm2java
 */

@Entity
@Table(name = "tb_tipo_proc_documento_trf")
@PrimaryKeyJoinColumn(name = "id_tipo_processo_documento_trf")
public class TipoProcessoDocumentoTrf extends TipoProcessoDocumento implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private Boolean habilitacaoAutos;
	private Boolean visivelAnaliseMinuta;
	private Integer prazoExpedienteAutomatico;
	private Integer tamanhoMaximoPagina;

	@Column(name = "in_habilitacao_autos")
	public Boolean getHabilitacaoAutos() {
		return habilitacaoAutos;
	}

	public void setHabilitacaoAutos(Boolean habilitacaoAutos) {
		this.habilitacaoAutos = habilitacaoAutos;
	}

	@Column(name = "in_visivel_analise_minuta")
	public Boolean getVisivelAnaliseMinuta() {
		return visivelAnaliseMinuta;
	}

	public void setVisivelAnaliseMinuta(Boolean visivelAnaliseMinuta) {
		this.visivelAnaliseMinuta = visivelAnaliseMinuta;
	}

	@Column(name = "nr_prazo_expediente_automatico")
	public Integer getPrazoExpedienteAutomatico() {
		return prazoExpedienteAutomatico;
	}

	public void setPrazoExpedienteAutomatico(Integer prazoExpedienteAutomatico) {
		this.prazoExpedienteAutomatico = prazoExpedienteAutomatico;
	}
	
	@Column(name = "tamanho_max_pagina")
	public Integer getTamanhoMaximoPagina() {
		return tamanhoMaximoPagina;
	}

	public void setTamanhoMaximoPagina(Integer tamanhoMaximoPagina) {
		this.tamanhoMaximoPagina = tamanhoMaximoPagina;
	}

	@Transient
	@Override
	public Class<? extends TipoProcessoDocumento> getEntityClass() {
		return TipoProcessoDocumentoTrf.class;
	}
}