package br.com.infox.pje.webservices.processoprevento;

import javax.xml.ws.WebFault;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3.2-06/22/2009 08:27
 * PM(mockbuild)-SNAPSHOT Generated source version: 2.0
 * 
 */
@WebFault(name = "UnsupportedEncodingException", targetNamespace = "http://webservices.pje.infox.com.br/")
public class UnsupportedEncodingException_Exception extends Exception {

	/**
	 * Java type that goes as soapenv:Fault detail element.
	 * 
	 */
	private UnsupportedEncodingException faultInfo;

	/**
	 * 
	 * @param message
	 * @param faultInfo
	 */
	public UnsupportedEncodingException_Exception(String message, UnsupportedEncodingException faultInfo) {
		super(message);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @param message
	 * @param faultInfo
	 * @param cause
	 */
	public UnsupportedEncodingException_Exception(String message, UnsupportedEncodingException faultInfo,
			Throwable cause) {
		super(message, cause);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @return returns fault bean:
	 *         br.com.infox.pje.webservices.UnsupportedEncodingException
	 */
	public UnsupportedEncodingException getFaultInfo() {
		return faultInfo;
	}

}
