package br.com.infox.pje.webservices.validaracesso;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3.2-02/08/2010 05:22
 * PM(mockbuild)-SNAPSHOT Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "ValidarAcessoService", targetNamespace = "http://webservices.pje.infox.com.br/", wsdlLocation = "http://localhost:8080/pje2_dev/ValidarAcesso?WSDL")
public class ValidarAcessoService extends Service {

	private final static URL VALIDARACESSOSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(br.com.infox.pje.webservices.validaracesso.ValidarAcessoService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = br.com.infox.pje.webservices.validaracesso.ValidarAcessoService.class.getResource(".");
			url = new URL(baseUrl, "http://localhost:8080/pje2_dev/ValidarAcesso?WSDL");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/pje2_dev/ValidarAcesso?WSDL', retrying as a local file");
			logger.warning(e.getMessage());
		}
		VALIDARACESSOSERVICE_WSDL_LOCATION = url;
	}

	public ValidarAcessoService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public ValidarAcessoService(URL wsdlLocation) {
		super(wsdlLocation, new QName("http://webservices.pje.infox.com.br/", "ValidarAcessoService"));
	}

	public ValidarAcessoService() {
		super(VALIDARACESSOSERVICE_WSDL_LOCATION, new QName("http://webservices.pje.infox.com.br/",
				"ValidarAcessoService"));
	}

	/**
	 * 
	 * @return returns ValidarAcesso
	 */
	@WebEndpoint(name = "ValidarAcessoPort")
	public ValidarAcesso getValidarAcessoPort() {
		return super.getPort(new QName("http://webservices.pje.infox.com.br/", "ValidarAcessoPort"),
				ValidarAcesso.class);
	}

}
