package br.gov.cjf.pj.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3.2-02/08/2010 05:22
 * PM(mockbuild)-SNAPSHOT Generated source version: 2.0
 * 
 */
@WebService(name = "wsConsultaCNPJ", targetNamespace = "http://webservice.cjf.gov.br/")
public interface WsConsultaCNPJ {

	/**
	 * 
	 * @param pNumCNPJ
	 * @param pNomeAplicacao
	 * @param pLoginUsuario
	 * @param pNomeOrgao
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "http://webservice.cjf.gov.br/")
	@RequestWrapper(localName = "getDadosCNPJSecurity", targetNamespace = "http://webservice.cjf.gov.br/", className = "br.gov.cjf.pj.webservice.GetDadosCNPJSecurity")
	@ResponseWrapper(localName = "getDadosCNPJSecurityResponse", targetNamespace = "http://webservice.cjf.gov.br/", className = "br.gov.cjf.pj.webservice.GetDadosCNPJSecurityResponse")
	public String getDadosCNPJSecurity(
			@WebParam(name = "pNumCNPJ", targetNamespace = "http://webservice.cjf.gov.br/") String pNumCNPJ,
			@WebParam(name = "pNomeOrgao", targetNamespace = "http://webservice.cjf.gov.br/") String pNomeOrgao,
			@WebParam(name = "pLoginUsuario", targetNamespace = "http://webservice.cjf.gov.br/") String pLoginUsuario,
			@WebParam(name = "pNomeAplicacao", targetNamespace = "http://webservice.cjf.gov.br/") String pNomeAplicacao);

	/**
	 * 
	 * @param pNumCNPJ
	 * @param pNomeAplicacao
	 * @param pLoginUsuario
	 * @param pNomeOrgao
	 * @return returns br.gov.cjf.pj.webservice.CNPJ
	 */
	@WebMethod
	@WebResult(targetNamespace = "http://webservice.cjf.gov.br/")
	@RequestWrapper(localName = "getObjectCNPJSecurity", targetNamespace = "http://webservice.cjf.gov.br/", className = "br.gov.cjf.pj.webservice.GetObjectCNPJSecurity")
	@ResponseWrapper(localName = "getObjectCNPJSecurityResponse", targetNamespace = "http://webservice.cjf.gov.br/", className = "br.gov.cjf.pj.webservice.GetObjectCNPJSecurityResponse")
	public CNPJ getObjectCNPJSecurity(
			@WebParam(name = "pNumCNPJ", targetNamespace = "http://webservice.cjf.gov.br/") String pNumCNPJ,
			@WebParam(name = "pNomeOrgao", targetNamespace = "http://webservice.cjf.gov.br/") String pNomeOrgao,
			@WebParam(name = "pLoginUsuario", targetNamespace = "http://webservice.cjf.gov.br/") String pLoginUsuario,
			@WebParam(name = "pNomeAplicacao", targetNamespace = "http://webservice.cjf.gov.br/") String pNomeAplicacao);

	/**
	 * 
	 * @param pNumCNPJ
	 * @param pNomeAplicacao
	 * @param pLoginUsuario
	 * @param pNomeOrgao
	 * @return returns boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "http://webservice.cjf.gov.br/")
	@RequestWrapper(localName = "setDadosCNPJSecurity", targetNamespace = "http://webservice.cjf.gov.br/", className = "br.gov.cjf.pj.webservice.SetDadosCNPJSecurity")
	@ResponseWrapper(localName = "setDadosCNPJSecurityResponse", targetNamespace = "http://webservice.cjf.gov.br/", className = "br.gov.cjf.pj.webservice.SetDadosCNPJSecurityResponse")
	public boolean setDadosCNPJSecurity(
			@WebParam(name = "pNumCNPJ", targetNamespace = "http://webservice.cjf.gov.br/") String pNumCNPJ,
			@WebParam(name = "pNomeOrgao", targetNamespace = "http://webservice.cjf.gov.br/") String pNomeOrgao,
			@WebParam(name = "pLoginUsuario", targetNamespace = "http://webservice.cjf.gov.br/") String pLoginUsuario,
			@WebParam(name = "pNomeAplicacao", targetNamespace = "http://webservice.cjf.gov.br/") String pNomeAplicacao);

	/**
	 * 
	 * @param pNumCNPJ
	 * @param pNomeAplicacao
	 * @param pLoginUsuario
	 * @param pNomeOrgao
	 * @return returns boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "http://webservice.cjf.gov.br/")
	@RequestWrapper(localName = "setObjectCNPJSecurity", targetNamespace = "http://webservice.cjf.gov.br/", className = "br.gov.cjf.pj.webservice.SetObjectCNPJSecurity")
	@ResponseWrapper(localName = "setObjectCNPJSecurityResponse", targetNamespace = "http://webservice.cjf.gov.br/", className = "br.gov.cjf.pj.webservice.SetObjectCNPJSecurityResponse")
	public boolean setObjectCNPJSecurity(
			@WebParam(name = "pNumCNPJ", targetNamespace = "http://webservice.cjf.gov.br/") String pNumCNPJ,
			@WebParam(name = "pNomeOrgao", targetNamespace = "http://webservice.cjf.gov.br/") String pNomeOrgao,
			@WebParam(name = "pLoginUsuario", targetNamespace = "http://webservice.cjf.gov.br/") String pLoginUsuario,
			@WebParam(name = "pNomeAplicacao", targetNamespace = "http://webservice.cjf.gov.br/") String pNomeAplicacao);

}
