package br.gov.cjf.pj.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3.2-02/08/2010 05:22
 * PM(mockbuild)-SNAPSHOT Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "wsConsultaCNPJ", targetNamespace = "http://webservice.cjf.gov.br/", wsdlLocation = "http://172.31.3.215:7778/wsConsultaCNPJ/wsConsultaCNPJSoapHttpPort?WSDL")
public class WsConsultaCNPJ_Service extends Service {

	private final static URL WSCONSULTACNPJ_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(br.gov.cjf.pj.webservice.WsConsultaCNPJ_Service.class
			.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = br.gov.cjf.pj.webservice.WsConsultaCNPJ_Service.class.getResource(".");
			url = new URL(baseUrl, "http://172.31.3.215:7778/wsConsultaCNPJ/wsConsultaCNPJSoapHttpPort?WSDL");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://172.31.3.215:7778/wsConsultaCNPJ/wsConsultaCNPJSoapHttpPort?WSDL', retrying as a local file");
			logger.warning(e.getMessage());
		}
		WSCONSULTACNPJ_WSDL_LOCATION = url;
	}

	public WsConsultaCNPJ_Service(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public WsConsultaCNPJ_Service() {
		super(WSCONSULTACNPJ_WSDL_LOCATION, new QName("http://webservice.cjf.gov.br/", "wsConsultaCNPJ"));
	}

	public WsConsultaCNPJ_Service(URL wsdlLocation) {
		super(wsdlLocation, new QName("http://webservice.cjf.gov.br/", "wsConsultaCNPJ"));
	}

	/**
	 * 
	 * @return returns WsConsultaCNPJ
	 */
	@WebEndpoint(name = "wsConsultaCNPJSoapHttpPort")
	public WsConsultaCNPJ getWsConsultaCNPJSoapHttpPort() {
		return super.getPort(new QName("http://webservice.cjf.gov.br/", "wsConsultaCNPJSoapHttpPort"),
				WsConsultaCNPJ.class);
	}

}
